<main class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">

            <h1 class="display-5 fw-semibold text-dark mt-3">Escritores de mi Latinoamérica</h1>



            <ul class="list-unstyled d-flex justify-content-center gap-3 mt-4">
                <li>
                    <a href="escritores" class="btn btn-outline-secondary btn-lg px-4">
                        Ver Escritores
                    </a>
                </li>
                <li>
                    <a href="libros" class="btn btn-secondary btn-lg px-4">
                        Ver Libros
                    </a>
                </li>
            </ul>

            <hr class="my-5 w-50 mx-auto border-secondary opacity-25">
            <p class="text-secondary-emphasis small">
                <i class="bi bi-quote"></i>
                literatura latinoamericana.
                <i class="bi bi-quote"></i>
            </p>
        </div>
    </div>
</main>